name:                aoc-visualizations
version:             0.1.0.0
github:              "Riddarvid/aoc-visualizations"
license:             BSD-3-Clause
author:              "Riddarvid"
maintainer:          "code@arvid-rydberg.se"
copyright:           "2024 Riddarvid"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Riddarvid/aoc-visualizations#readme>

dependencies:
- base >= 4.7 && < 5
- aoc-utils >= 0.1.0.0
- aoc2023 >= 0.1.0.0
- containers >= 0.6.7
- unordered-containers >= 0.2.19.1
- linear >= 1.22
- gloss >= 1.13.2.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc-visualizations-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-visualizations

tests:
  aoc-visualizations-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-visualizations
